//package mmo.db.role.entity;
//
//import mmo.db.DbEntity;
//import mmo.db.trans.TransLog;
//import mmo.db.trans.Transaction;
//import mmo.db.MapperMgr;
//import mmo.db.role.mapper.RoleMapper;
//
//public class Role2 extends DbEntity {
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column role.id
//     *
//     * @mbggenerated Sun Aug 14 19:00:26 CST 2016
//     */
//    private Integer id;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column role.nickname
//     *
//     * @mbggenerated Sun Aug 14 19:00:26 CST 2016
//     */
//    private String nickname;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column role.level
//     *
//     * @mbggenerated Sun Aug 14 19:00:26 CST 2016
//     */
//    private Integer level;
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table role
//     *
//     * @mbggenerated Sun Aug 14 19:00:26 CST 2016
//     */
//    public Role(Integer id, String nickname, Integer level) {
//        this.id = id;
//        this.nickname = nickname;
//        this.level = level;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table role
//     *
//     * @mbggenerated Sun Aug 14 19:00:26 CST 2016
//     */
//    public Role() {
//        super();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column role.id
//     *
//     * @return the value of role.id
//     * @mbggenerated Sun Aug 14 19:00:26 CST 2016
//     */
//    public Integer getId() {
//        return id;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column role.id
//     *
//     * @param id the value for role.id
//     * @mbggenerated Sun Aug 14 19:00:26 CST 2016
//     */
//    public void setId(final Integer id) {
//        if (this.id != null && this.id.equals(id)) {
//            return;
//        }
//        Transaction transaction = Transaction.current();
//        if (transaction == null || isMirror) {
//            this.id = id;
//            Role role = getMirror();
//            role.setId(id);
//            role.onUpdate();
//            return;
//        }
//        final Integer curr = this.id;
//        transaction.addTRecord(new TransLog() {
//            @Override
//            public void commit() {
//                Role role = getMirror();
//                role.setId(id);
//                role.onUpdate();
//            }
//
//            @Override
//            public void rollback() {
//                Role.this.id = curr;
//            }
//        });
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column role.nickname
//     *
//     * @return the value of role.nickname
//     * @mbggenerated Sun Aug 14 19:00:26 CST 2016
//     */
//    public String getNickname() {
//        return nickname;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column role.nickname
//     *
//     * @param nickname the value for role.nickname
//     * @mbggenerated Sun Aug 14 19:00:26 CST 2016
//     */
//    public void setNickname(final String nickname) {
//        if (this.nickname != null && this.nickname.equals(nickname)) {
//            return;
//        }
//        Transaction transaction = Transaction.current();
//        if (transaction == null || isMirror) {
//            this.nickname = nickname == null ? null : nickname.trim();
//            Role role = getMirror();
//            role.setNickname(nickname);
//            role.onUpdate();
//            return;
//        }
//        final String curr = this.nickname;
//        transaction.addTRecord(new TransLog() {
//            @Override
//            public void commit() {
//                Role role = getMirror();
//                role.setNickname(nickname);
//                role.onUpdate();
//            }
//
//            @Override
//            public void rollback() {
//                Role.this.nickname = curr;
//            }
//        });
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column role.level
//     *
//     * @return the value of role.level
//     * @mbggenerated Sun Aug 14 19:00:26 CST 2016
//     */
//    public Integer getLevel() {
//        return level;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column role.level
//     *
//     * @param level the value for role.level
//     * @mbggenerated Sun Aug 14 19:00:26 CST 2016
//     */
//    public void setLevel(final Integer level) {
//        if (this.level != null && this.level.equals(level)) {
//            return;
//        }
//        if(isMirror){
//            this.level = level;
//            return;
//        }
//        Transaction transaction = Transaction.current();
//        if (transaction != null) {
//            final Integer curr = this.level;
//            transaction.addTRecord(new TransLog() {
//                @Override
//                public void commit() {
//                    Role role = getMirror();
//                    role.setLevel(level);
//                    role.onUpdate();
//                }
//
//                @Override
//                public void rollback() {
//                    Role.this.level = curr;
//                }
//            });
//        } else {
//            Role role = getMirror();
//            role.setLevel(level);
//            role.onUpdate();
//        }
//        this.level = level;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table role
//     *
//     * @mbggenerated Sun Aug 14 19:00:26 CST 2016
//     */
//    @Override
//    public void update() {
//        Role mirror = getMirror();
//        MapperMgr.getMapper(RoleMapper.class).updateByPrimaryKeySelective(mirror);
//        nickname = null;
//        level = null;
//        mirror.resetMark();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table role
//     *
//     * @mbggenerated Sun Aug 14 19:00:26 CST 2016
//     */
//    @Override
//    public void initMirror() {
//        Role role = new Role();
//        role.isMirror = true;
//        mirror = role;
//    }
//}